import type { Metadata } from "next";
import "./globals.css";
// import "../styles/globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className="flex flex-row justify-evenly items-center">
          <Link href="/">홈</Link>
          <Link href="/champions">챔피언 목록</Link>
          <Link href="/items">아이템 목록</Link>
          <Link href="/rotation">챔피언 로테이션</Link>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
